nelmio_security:
    csp:
        enforce:
            script-src:
                - 'self'
                - 'unsafe-inline'
                - 'unsafe-eval'
                - 'https://polyfill.io'
                - 'https://js.stripe.com'
                - 'https://cdn.jsdelivr.net'
